import numpy as np
import statsmodels.api as sm
import pandas as pd

import quantopian.optimize as opt
import quantopian.algorithm as algo

def initialize(context):
    # Quantopian backtester specific variables
    set_slippage(slippage.FixedSlippage(spread=0))
    set_commission(commission.PerTrade(cost=0.00))
    set_symbol_lookup_date('2020-09-01')
    
    context.stock_pairs = [(symbol('DIA'), symbol('MINT')),
(symbol('DIA'), symbol('NEAR')),
(symbol('DIA'), symbol('FTSM')),
(symbol('SPY'), symbol('IVV')),
(symbol('SPY'), symbol('IWB')),
(symbol('SPY'), symbol('VV')),
(symbol('SPY'), symbol('FEZ')),
(symbol('SPY'), symbol('SCHX')),
(symbol('SPY'), symbol('MINT')),
(symbol('SPY'), symbol('VOO')),
(symbol('SPY'), symbol('VIXY')),
(symbol('SPY'), symbol('NEAR')),
(symbol('SPY'), symbol('FTSM')),
(symbol('MDY'), symbol('IJH')),
(symbol('MDY'), symbol('VEA')),
(symbol('MDY'), symbol('SCHF')),
(symbol('EWA'), symbol('QQQ')),
(symbol('EWA'), symbol('IVV')),
(symbol('EWA'), symbol('IVW')),
(symbol('EWA'), symbol('IWB')),
(symbol('EWA'), symbol('IWF')),
(symbol('EWA'), symbol('IWV')),
(symbol('EWA'), symbol('IYF')),
(symbol('EWA'), symbol('IUSG')),
(symbol('EWA'), symbol('SPYG')),
(symbol('EWA'), symbol('OEF')),
(symbol('EWA'), symbol('VTI')),
(symbol('EWA'), symbol('ITOT')),
(symbol('EWA'), symbol('VO')),
(symbol('EWA'), symbol('VUG')),
(symbol('EWA'), symbol('VV')),
(symbol('EWA'), symbol('FAS')),
(symbol('EWA'), symbol('SCHB')),
(symbol('EWA'), symbol('SCHX')),
(symbol('EWA'), symbol('MINT')),
(symbol('EWA'), symbol('SCHG')),
(symbol('EWA'), symbol('VOO')),
(symbol('EWA'), symbol('VIXY')),
(symbol('EWA'), symbol('MTUM')),
(symbol('EWA'), symbol('NEAR')),
(symbol('EWA'), symbol('DGRO')),
(symbol('EWA'), symbol('FTSM')),
(symbol('EWA'), symbol('XLC')),
(symbol('EWC'), symbol('XLI')),
(symbol('EWC'), symbol('IWV')),
(symbol('EWC'), symbol('VTI')),
(symbol('EWC'), symbol('RSP')),
(symbol('EWC'), symbol('ITOT')),
(symbol('EWC'), symbol('VTV')),
(symbol('EWC'), symbol('FEZ')),
(symbol('EWC'), symbol('VYM')),
(symbol('EWC'), symbol('ACWI')),
(symbol('EWC'), symbol('VT')),
(symbol('EWC'), symbol('CWB')),
(symbol('EWC'), symbol('SCHB')),
(symbol('EWC'), symbol('MINT')),
(symbol('EWC'), symbol('NEAR')),
(symbol('EWC'), symbol('FTSM')),
(symbol('EWC'), symbol('HYLB')),
(symbol('EWG'), symbol('IWM')),
(symbol('EWG'), symbol('SCZ')),
(symbol('EWG'), symbol('TNA')),
(symbol('EWG'), symbol('AMJ')),
(symbol('EWG'), symbol('AMLP')),
(symbol('EWG'), symbol('FLOT')),
(symbol('EWG'), symbol('FLRN')),
(symbol('EWJ'), symbol('XLE')),
(symbol('EWU'), symbol('FLRN')),
(symbol('EWW'), symbol('AMLP')),
(symbol('XLE'), symbol('DXJ')),
(symbol('XLF'), symbol('FTSM')),
(symbol('XLI'), symbol('FTSM')),
(symbol('XLK'), symbol('MINT')),
(symbol('XLK'), symbol('NEAR')),
(symbol('XLK'), symbol('FTSM')),
(symbol('XLU'), symbol('SHV')),
(symbol('XLU'), symbol('GBIL')),
(symbol('XLU'), symbol('JPST')),
(symbol('XLY'), symbol('NEAR')),
(symbol('XLY'), symbol('FTSM')),
(symbol('QQQ'), symbol('FEZ')),
(symbol('QQQ'), symbol('MINT')),
(symbol('QQQ'), symbol('VIXY')),
(symbol('QQQ'), symbol('NEAR')),
(symbol('QQQ'), symbol('FTSM')),
(symbol('QQQ'), symbol('XLC')),
(symbol('IJH'), symbol('VEA')),
(symbol('IJR'), symbol('KRE')),
(symbol('IVE'), symbol('SPYV')),
(symbol('IVE'), symbol('CWB')),
(symbol('IVE'), symbol('MINT')),
(symbol('IVE'), symbol('FTSM')),
(symbol('IVV'), symbol('VV')),
(symbol('IVV'), symbol('FEZ')),
(symbol('IVV'), symbol('SCHX')),
(symbol('IVV'), symbol('MINT')),
(symbol('IVV'), symbol('VOO')),
(symbol('IVV'), symbol('VIXY')),
(symbol('IVV'), symbol('NEAR')),
(symbol('IVV'), symbol('FTSM')),
(symbol('IVW'), symbol('SPYG')),
(symbol('IVW'), symbol('FEZ')),
(symbol('IVW'), symbol('MINT')),
(symbol('IVW'), symbol('VIXY')),
(symbol('IVW'), symbol('NEAR')),
(symbol('IVW'), symbol('FTSM')),
(symbol('IWB'), symbol('VV')),
(symbol('IWB'), symbol('FEZ')),
(symbol('IWB'), symbol('SCHX')),
(symbol('IWB'), symbol('MINT')),
(symbol('IWB'), symbol('VIXY')),
(symbol('IWB'), symbol('NEAR')),
(symbol('IWB'), symbol('FTSM')),
(symbol('IWD'), symbol('VTV')),
(symbol('IWD'), symbol('CWB')),
(symbol('IWD'), symbol('MINT')),
(symbol('IWD'), symbol('FTSM')),
(symbol('IWF'), symbol('VUG')),
(symbol('IWF'), symbol('FEZ')),
(symbol('IWF'), symbol('MINT')),
(symbol('IWF'), symbol('VIXY')),
(symbol('IWF'), symbol('NEAR')),
(symbol('IWF'), symbol('FTSM')),
(symbol('IWM'), symbol('VBR')),
(symbol('IWM'), symbol('SCZ')),
(symbol('IWM'), symbol('VSS')),
(symbol('IWV'), symbol('VTI')),
(symbol('IWV'), symbol('ITOT')),
(symbol('IWV'), symbol('FEZ')),
(symbol('IWV'), symbol('SCHB')),
(symbol('IWV'), symbol('MINT')),
(symbol('IWV'), symbol('DBEF')),
(symbol('IWV'), symbol('NEAR')),
(symbol('IWV'), symbol('FTSM')),
(symbol('IYF'), symbol('MINT')),
(symbol('IYF'), symbol('NEAR')),
(symbol('IYF'), symbol('FTSM')),
(symbol('EWT'), symbol('TQQQ')),
(symbol('IYR'), symbol('SHV')),
(symbol('IYR'), symbol('JPST')),
(symbol('EZU'), symbol('IWO')),
(symbol('EZU'), symbol('VXF')),
(symbol('EZU'), symbol('VB')),
(symbol('EZU'), symbol('QLD')),
(symbol('EZU'), symbol('SPDW')),
(symbol('EZU'), symbol('MINT')),
(symbol('EZU'), symbol('TQQQ')),
(symbol('EZU'), symbol('FLOT')),
(symbol('EZU'), symbol('FLRN')),
(symbol('EZU'), symbol('SJNK')),
(symbol('EZU'), symbol('IEFA')),
(symbol('IWN'), symbol('KRE')),
(symbol('IWO'), symbol('VGK')),
(symbol('IWO'), symbol('SPDW')),
(symbol('IWO'), symbol('VEA')),
(symbol('IWO'), symbol('SCHF')),
(symbol('IWO'), symbol('IEFA')),
(symbol('IUSV'), symbol('SPYV')),
(symbol('IUSV'), symbol('CWB')),
(symbol('IUSV'), symbol('MINT')),
(symbol('IUSV'), symbol('FTSM')),
(symbol('IUSG'), symbol('FEZ')),
(symbol('IUSG'), symbol('MINT')),
(symbol('IUSG'), symbol('VIXY')),
(symbol('IUSG'), symbol('DBEF')),
(symbol('IUSG'), symbol('NEAR')),
(symbol('IUSG'), symbol('FTSM')),
(symbol('SPYG'), symbol('FEZ')),
(symbol('SPYG'), symbol('MINT')),
(symbol('SPYG'), symbol('VIXY')),
(symbol('SPYG'), symbol('NEAR')),
(symbol('SPYG'), symbol('FTSM')),
(symbol('SPYV'), symbol('CWB')),
(symbol('SPYV'), symbol('MINT')),
(symbol('SPYV'), symbol('FTSM')),
(symbol('OEF'), symbol('FEZ')),
(symbol('OEF'), symbol('MINT')),
(symbol('OEF'), symbol('DBEF')),
(symbol('OEF'), symbol('NEAR')),
(symbol('OEF'), symbol('FTSM')),
(symbol('VTI'), symbol('ITOT')),
(symbol('VTI'), symbol('FEZ')),
(symbol('VTI'), symbol('SCHB')),
(symbol('VTI'), symbol('MINT')),
(symbol('VTI'), symbol('NEAR')),
(symbol('VTI'), symbol('FTSM')),
(symbol('IGV'), symbol('EMB')),
(symbol('IGV'), symbol('NEAR')),
(symbol('IGV'), symbol('FTSM')),
(symbol('IGV'), symbol('JPST')),
(symbol('IWP'), symbol('XHB')),
(symbol('IWP'), symbol('QID')),
(symbol('IWP'), symbol('SPXS')),
(symbol('IWP'), symbol('NEAR')),
(symbol('IWP'), symbol('FTSM')),
(symbol('IWR'), symbol('EMLC')),
(symbol('IWS'), symbol('CWB')),
(symbol('EFA'), symbol('VXF')),
(symbol('EFA'), symbol('VB')),
(symbol('EFA'), symbol('VGK')),
(symbol('EFA'), symbol('SPDW')),
(symbol('EFA'), symbol('MINT')),
(symbol('EFA'), symbol('TQQQ')),
(symbol('EFA'), symbol('FLRN')),
(symbol('VXF'), symbol('VGK')),
(symbol('VXF'), symbol('VEU')),
(symbol('VXF'), symbol('VEA')),
(symbol('VXF'), symbol('VXUS')),
(symbol('IEF'), symbol('SHY')),
(symbol('IEF'), symbol('SHV')),
(symbol('IEF'), symbol('VGSH')),
(symbol('IEF'), symbol('SCHO')),
(symbol('IEF'), symbol('GBIL')),
(symbol('LQD'), symbol('JPST')),
(symbol('SHY'), symbol('IEI')),
(symbol('SHY'), symbol('SHV')),
(symbol('SHY'), symbol('VGSH')),
(symbol('SHY'), symbol('SCHO')),
(symbol('SHY'), symbol('DGAZ')),
(symbol('SHY'), symbol('GOVT')),
(symbol('SHY'), symbol('GBIL')),
(symbol('SHY'), symbol('JPST')),
(symbol('EZA'), symbol('RSP')),
(symbol('EZA'), symbol('AGG')),
(symbol('EZA'), symbol('DVY')),
(symbol('EZA'), symbol('TIP')),
(symbol('EZA'), symbol('ITOT')),
(symbol('EZA'), symbol('VB')),
(symbol('EZA'), symbol('VBR')),
(symbol('EZA'), symbol('VFH')),
(symbol('EZA'), symbol('VGT')),
(symbol('EZA'), symbol('VHT')),
(symbol('EZA'), symbol('VO')),
(symbol('EZA'), symbol('VTV')),
(symbol('EZA'), symbol('VUG')),
(symbol('EZA'), symbol('VV')),
(symbol('EZA'), symbol('VNQ')),
(symbol('EZA'), symbol('FXI')),
(symbol('EZA'), symbol('GLD')),
(symbol('EZA'), symbol('IAU')),
(symbol('EZA'), symbol('VWO')),
(symbol('EZA'), symbol('KBE')),
(symbol('EZA'), symbol('SDY')),
(symbol('EZA'), symbol('XBI')),
(symbol('EZA'), symbol('XHB')),
(symbol('EZA'), symbol('USO')),
(symbol('EZA'), symbol('VIG')),
(symbol('EZA'), symbol('ITB')),
(symbol('EZA'), symbol('ITA')),
(symbol('EZA'), symbol('GDX')),
(symbol('EZA'), symbol('PSQ')),
(symbol('EZA'), symbol('DOG')),
(symbol('EZA'), symbol('SH')),
(symbol('EZA'), symbol('DDM')),
(symbol('EZA'), symbol('SSO')),
(symbol('EZA'), symbol('QLD')),
(symbol('EZA'), symbol('XRT')),
(symbol('EZA'), symbol('KRE')),
(symbol('EZA'), symbol('XOP')),
(symbol('EZA'), symbol('FDN')),
(symbol('EZA'), symbol('QID')),
(symbol('EZA'), symbol('SDS')),
(symbol('EZA'), symbol('VOE')),
(symbol('EZA'), symbol('PFF')),
(symbol('EZA'), symbol('VYM')),
(symbol('EZA'), symbol('IGSB')),
(symbol('EZA'), symbol('IEI')),
(symbol('EZA'), symbol('SHV')),
(symbol('EZA'), symbol('MBB')),
(symbol('EZA'), symbol('BLV')),
(symbol('EZA'), symbol('BIV')),
(symbol('EZA'), symbol('BSV')),
(symbol('EZA'), symbol('BND')),
(symbol('EZA'), symbol('HYG')),
(symbol('EZA'), symbol('UNG')),
(symbol('EZA'), symbol('BIL')),
(symbol('EZA'), symbol('DXJ')),
(symbol('EZA'), symbol('MUB')),
(symbol('EZA'), symbol('PCY')),
(symbol('EZA'), symbol('JNK')),
(symbol('EZA'), symbol('EMB')),
(symbol('EZA'), symbol('EPI')),
(symbol('EZA'), symbol('ACWI')),
(symbol('EZA'), symbol('TBT')),
(symbol('EZA'), symbol('VT')),
(symbol('EZA'), symbol('AAXJ')),
(symbol('EZA'), symbol('FAS')),
(symbol('EZA'), symbol('SPXS')),
(symbol('EZA'), symbol('TZA')),
(symbol('EZA'), symbol('ERX')),
(symbol('EZA'), symbol('SPXL')),
(symbol('EZA'), symbol('TNA')),
(symbol('EZA'), symbol('UCO')),
(symbol('EZA'), symbol('SCO')),
(symbol('EZA'), symbol('SPIB')),
(symbol('EZA'), symbol('AMJ')),
(symbol('EZA'), symbol('CWB')),
(symbol('EZA'), symbol('SPXU')),
(symbol('EZA'), symbol('UPRO')),
(symbol('EZA'), symbol('SCHB')),
(symbol('EZA'), symbol('SCHX')),
(symbol('EZA'), symbol('GDXJ')),
(symbol('EZA'), symbol('MINT')),
(symbol('EZA'), symbol('VMBS')),
(symbol('EZA'), symbol('VCSH')),
(symbol('EZA'), symbol('VGSH')),
(symbol('EZA'), symbol('VCIT')),
(symbol('EZA'), symbol('SCHG')),
(symbol('EZA'), symbol('SPSB')),
(symbol('EZA'), symbol('SQQQ')),
(symbol('EZA'), symbol('SDOW')),
(symbol('EZA'), symbol('TQQQ')),
(symbol('EZA'), symbol('UDOW')),
(symbol('EZA'), symbol('SOXL')),
(symbol('EZA'), symbol('SOXS')),
(symbol('EZA'), symbol('EMLC')),
(symbol('EZA'), symbol('SCHO')),
(symbol('EZA'), symbol('AMLP')),
(symbol('EZA'), symbol('VOO')),
(symbol('EZA'), symbol('TVIX')),
(symbol('EZA'), symbol('NUGT')),
(symbol('EZA'), symbol('DUST')),
(symbol('EZA'), symbol('VIXY')),
(symbol('EZA'), symbol('BKLN')),
(symbol('EZA'), symbol('HDV')),
(symbol('EZA'), symbol('MCHI')),
(symbol('EZA'), symbol('SPLV')),
(symbol('EZA'), symbol('DBEF')),
(symbol('EZA'), symbol('FLOT')),
(symbol('EZA'), symbol('SCHZ')),
(symbol('EZA'), symbol('SVXY')),
(symbol('EZA'), symbol('UVXY')),
(symbol('EZA'), symbol('EEMV')),
(symbol('EZA'), symbol('USMV')),
(symbol('EZA'), symbol('EFAV')),
(symbol('EZA'), symbol('SCHD')),
(symbol('EZA'), symbol('FLRN')),
(symbol('EZA'), symbol('OIH')),
(symbol('EZA'), symbol('SMH')),
(symbol('EZA'), symbol('INDA')),
(symbol('EZA'), symbol('DGAZ')),
(symbol('EZA'), symbol('GOVT')),
(symbol('EZA'), symbol('SJNK')),
(symbol('EZA'), symbol('BRZU')),
(symbol('EZA'), symbol('MTUM')),
(symbol('EZA'), symbol('VLUE')),
(symbol('EZA'), symbol('BNDX')),
(symbol('EZA'), symbol('QUAL')),
(symbol('EZA'), symbol('NEAR')),
(symbol('EZA'), symbol('JNUG')),
(symbol('EZA'), symbol('JDST')),
(symbol('EZA'), symbol('NOBL')),
(symbol('EZA'), symbol('ASHR')),
(symbol('EZA'), symbol('DGRO')),
(symbol('EZA'), symbol('FTSM')),
(symbol('EZA'), symbol('LABD')),
(symbol('EZA'), symbol('LABU')),
(symbol('EZA'), symbol('DRIP')),
(symbol('EZA'), symbol('GUSH')),
(symbol('EZA'), symbol('XLRE')),
(symbol('EZA'), symbol('GBIL')),
(symbol('EZA'), symbol('HYLB')),
(symbol('EZA'), symbol('DWT')),
(symbol('EZA'), symbol('UWT')),
(symbol('EZA'), symbol('JPST')),
(symbol('EZA'), symbol('XLC')),
(symbol('EEM'), symbol('LABD')),
(symbol('RSP'), symbol('NEAR')),
(symbol('RSP'), symbol('FTSM')),
(symbol('AGG'), symbol('SHV')),
(symbol('AGG'), symbol('BND')),
(symbol('AGG'), symbol('SCHZ')),
(symbol('AGG'), symbol('GBIL')),
(symbol('AGG'), symbol('JPST')),
(symbol('DVY'), symbol('VOE')),
(symbol('DVY'), symbol('CWB')),
(symbol('TIP'), symbol('JPST')),
(symbol('ITOT'), symbol('FEZ')),
(symbol('ITOT'), symbol('SCHB')),
(symbol('ITOT'), symbol('MINT')),
(symbol('ITOT'), symbol('DBEF')),
(symbol('ITOT'), symbol('NEAR')),
(symbol('ITOT'), symbol('FTSM')),
(symbol('VB'), symbol('VGK')),
(symbol('VB'), symbol('VEU')),
(symbol('VB'), symbol('SPDW')),
(symbol('VB'), symbol('VEA')),
(symbol('VB'), symbol('VXUS')),
(symbol('VB'), symbol('IXUS')),
(symbol('VBR'), symbol('KBE')),
(symbol('VGT'), symbol('NEAR')),
(symbol('VGT'), symbol('FTSM')),
(symbol('VO'), symbol('VIXY')),
(symbol('VO'), symbol('NEAR')),
(symbol('VO'), symbol('FTSM')),
(symbol('VTV'), symbol('CWB')),
(symbol('VTV'), symbol('MINT')),
(symbol('VTV'), symbol('FTSM')),
(symbol('VUG'), symbol('FEZ')),
(symbol('VUG'), symbol('MINT')),
(symbol('VUG'), symbol('VIXY')),
(symbol('VUG'), symbol('NEAR')),
(symbol('VUG'), symbol('FTSM')),
(symbol('VV'), symbol('FEZ')),
(symbol('VV'), symbol('SCHX')),
(symbol('VV'), symbol('MINT')),
(symbol('VV'), symbol('VOO')),
(symbol('VV'), symbol('VIXY')),
(symbol('VV'), symbol('NEAR')),
(symbol('VV'), symbol('FTSM')),
(symbol('FEZ'), symbol('PSQ')),
(symbol('FEZ'), symbol('SH')),
(symbol('FEZ'), symbol('SSO')),
(symbol('FEZ'), symbol('QLD')),
(symbol('FEZ'), symbol('FDN')),
(symbol('FEZ'), symbol('QID')),
(symbol('FEZ'), symbol('SDS')),
(symbol('FEZ'), symbol('VYM')),
(symbol('FEZ'), symbol('HYG')),
(symbol('FEZ'), symbol('ACWI')),
(symbol('FEZ'), symbol('VT')),
(symbol('FEZ'), symbol('SPXS')),
(symbol('FEZ'), symbol('SPXL')),
(symbol('FEZ'), symbol('CWB')),
(symbol('FEZ'), symbol('SPXU')),
(symbol('FEZ'), symbol('UPRO')),
(symbol('FEZ'), symbol('SCHB')),
(symbol('FEZ'), symbol('SCHX')),
(symbol('FEZ'), symbol('MINT')),
(symbol('FEZ'), symbol('SCHG')),
(symbol('FEZ'), symbol('TQQQ')),
(symbol('FEZ'), symbol('VOO')),
(symbol('FEZ'), symbol('TVIX')),
(symbol('FEZ'), symbol('VIXY')),
(symbol('FEZ'), symbol('DBEF')),
(symbol('FEZ'), symbol('SCHD')),
(symbol('FEZ'), symbol('MTUM')),
(symbol('FEZ'), symbol('QUAL')),
(symbol('FEZ'), symbol('NEAR')),
(symbol('FEZ'), symbol('DGRO')),
(symbol('FEZ'), symbol('FTSM')),
(symbol('FEZ'), symbol('HYLB')),
(symbol('FEZ'), symbol('XLC')),
(symbol('VNQ'), symbol('JPST')),
(symbol('GLD'), symbol('IAU')),
(symbol('GLD'), symbol('GBIL')),
(symbol('IAU'), symbol('GBIL')),
(symbol('VGK'), symbol('QLD')),
(symbol('VGK'), symbol('SPDW')),
(symbol('VGK'), symbol('MINT')),
(symbol('VGK'), symbol('TQQQ')),
(symbol('VGK'), symbol('FLRN')),
(symbol('VWO'), symbol('LABD')),
(symbol('SDY'), symbol('TVIX')),
(symbol('SDY'), symbol('NEAR')),
(symbol('SDY'), symbol('FTSM')),
(symbol('XBI'), symbol('VSS')),
(symbol('XHB'), symbol('FDN')),
(symbol('VIG'), symbol('NEAR')),
(symbol('VIG'), symbol('FTSM')),
(symbol('ITB'), symbol('FDN')),
(symbol('ITA'), symbol('MINT')),
(symbol('ITA'), symbol('NEAR')),
(symbol('ITA'), symbol('FTSM')),
(symbol('PSQ'), symbol('VIXY')),
(symbol('PSQ'), symbol('NEAR')),
(symbol('PSQ'), symbol('FTSM')),
(symbol('DOG'), symbol('NEAR')),
(symbol('DOG'), symbol('FTSM')),
(symbol('SH'), symbol('MINT')),
(symbol('SH'), symbol('VIXY')),
(symbol('SH'), symbol('NEAR')),
(symbol('SH'), symbol('FTSM')),
(symbol('DDM'), symbol('MINT')),
(symbol('DDM'), symbol('FTSM')),
(symbol('SSO'), symbol('MINT')),
(symbol('SSO'), symbol('FTSM')),
(symbol('QLD'), symbol('MINT')),
(symbol('QLD'), symbol('DBEF')),
(symbol('QLD'), symbol('FTSM')),
(symbol('XME'), symbol('XRT')),
(symbol('FDN'), symbol('HYG')),
(symbol('FDN'), symbol('EFAV')),
(symbol('FDN'), symbol('NEAR')),
(symbol('FDN'), symbol('FTSM')),
(symbol('FDN'), symbol('HYLB')),
(symbol('QID'), symbol('TVIX')),
(symbol('QID'), symbol('NEAR')),
(symbol('QID'), symbol('FTSM')),
(symbol('QID'), symbol('JPST')),
(symbol('SDS'), symbol('TVIX')),
(symbol('SDS'), symbol('VIXY')),
(symbol('SDS'), symbol('NEAR')),
(symbol('SDS'), symbol('FTSM')),
(symbol('VOE'), symbol('CWB')),
(symbol('PFF'), symbol('FTSM')),
(symbol('VYM'), symbol('CWB')),
(symbol('VYM'), symbol('MINT')),
(symbol('VYM'), symbol('DBEF')),
(symbol('VYM'), symbol('FTSM')),
(symbol('IGSB'), symbol('IEI')),
(symbol('IGSB'), symbol('SHV')),
(symbol('IGSB'), symbol('VEU')),
(symbol('IGSB'), symbol('MBB')),
(symbol('IGSB'), symbol('BLV')),
(symbol('IGSB'), symbol('BIV')),
(symbol('IGSB'), symbol('BSV')),
(symbol('IGSB'), symbol('BND')),
(symbol('IGSB'), symbol('HYG')),
(symbol('IGSB'), symbol('UNG')),
(symbol('IGSB'), symbol('SPDW')),
(symbol('IGSB'), symbol('RSX')),
(symbol('IGSB'), symbol('BIL')),
(symbol('IGSB'), symbol('DXJ')),
(symbol('IGSB'), symbol('VEA')),
(symbol('IGSB'), symbol('MUB')),
(symbol('IGSB'), symbol('PCY')),
(symbol('IGSB'), symbol('JNK')),
(symbol('IGSB'), symbol('SCZ')),
(symbol('IGSB'), symbol('EMB')),
(symbol('IGSB'), symbol('EPI')),
(symbol('IGSB'), symbol('ACWI')),
(symbol('IGSB'), symbol('ACWX')),
(symbol('IGSB'), symbol('TBT')),
(symbol('IGSB'), symbol('VT')),
(symbol('IGSB'), symbol('AAXJ')),
(symbol('IGSB'), symbol('FAS')),
(symbol('IGSB'), symbol('SPXS')),
(symbol('IGSB'), symbol('TZA')),
(symbol('IGSB'), symbol('ERX')),
(symbol('IGSB'), symbol('SPXL')),
(symbol('IGSB'), symbol('TNA')),
(symbol('IGSB'), symbol('UCO')),
(symbol('IGSB'), symbol('SCO')),
(symbol('IGSB'), symbol('SPIB')),
(symbol('IGSB'), symbol('AMJ')),
(symbol('IGSB'), symbol('VSS')),
(symbol('IGSB'), symbol('CWB')),
(symbol('IGSB'), symbol('SPXU')),
(symbol('IGSB'), symbol('UPRO')),
(symbol('IGSB'), symbol('SCHB')),
(symbol('IGSB'), symbol('SCHX')),
(symbol('IGSB'), symbol('SCHF')),
(symbol('IGSB'), symbol('GDXJ')),
(symbol('IGSB'), symbol('MINT')),
(symbol('IGSB'), symbol('VMBS')),
(symbol('IGSB'), symbol('VCSH')),
(symbol('IGSB'), symbol('VGSH')),
(symbol('IGSB'), symbol('VCIT')),
(symbol('IGSB'), symbol('YINN')),
(symbol('IGSB'), symbol('SCHG')),
(symbol('IGSB'), symbol('SPSB')),
(symbol('IGSB'), symbol('SCHE')),
(symbol('IGSB'), symbol('SQQQ')),
(symbol('IGSB'), symbol('SDOW')),
(symbol('IGSB'), symbol('TQQQ')),
(symbol('IGSB'), symbol('UDOW')),
(symbol('IGSB'), symbol('SOXL')),
(symbol('IGSB'), symbol('SOXS')),
(symbol('IGSB'), symbol('EMLC')),
(symbol('IGSB'), symbol('SCHO')),
(symbol('IGSB'), symbol('AMLP')),
(symbol('IGSB'), symbol('VOO')),
(symbol('IGSB'), symbol('TVIX')),
(symbol('IGSB'), symbol('NUGT')),
(symbol('IGSB'), symbol('DUST')),
(symbol('IGSB'), symbol('VIXY')),
(symbol('IGSB'), symbol('VXUS')),
(symbol('IGSB'), symbol('BKLN')),
(symbol('IGSB'), symbol('HDV')),
(symbol('IGSB'), symbol('MCHI')),
(symbol('IGSB'), symbol('SPLV')),
(symbol('IGSB'), symbol('DBEF')),
(symbol('IGSB'), symbol('FLOT')),
(symbol('IGSB'), symbol('SCHZ')),
(symbol('IGSB'), symbol('SVXY')),
(symbol('IGSB'), symbol('UVXY')),
(symbol('IGSB'), symbol('EEMV')),
(symbol('IGSB'), symbol('USMV')),
(symbol('IGSB'), symbol('EFAV')),
(symbol('IGSB'), symbol('SCHD')),
(symbol('IGSB'), symbol('FLRN')),
(symbol('IGSB'), symbol('OIH')),
(symbol('IGSB'), symbol('SMH')),
(symbol('IGSB'), symbol('INDA')),
(symbol('IGSB'), symbol('DGAZ')),
(symbol('IGSB'), symbol('GOVT')),
(symbol('IGSB'), symbol('SJNK')),
(symbol('IGSB'), symbol('IXUS')),
(symbol('IGSB'), symbol('IEFA')),
(symbol('IGSB'), symbol('IEMG')),
(symbol('IGSB'), symbol('BRZU')),
(symbol('IGSB'), symbol('MTUM')),
(symbol('IGSB'), symbol('VLUE')),
(symbol('IGSB'), symbol('BNDX')),
(symbol('IGSB'), symbol('QUAL')),
(symbol('IGSB'), symbol('KWEB')),
(symbol('IGSB'), symbol('NEAR')),
(symbol('IGSB'), symbol('JNUG')),
(symbol('IGSB'), symbol('JDST')),
(symbol('IGSB'), symbol('NOBL')),
(symbol('IGSB'), symbol('ASHR')),
(symbol('IGSB'), symbol('DGRO')),
(symbol('IGSB'), symbol('FTSM')),
(symbol('IGSB'), symbol('LABD')),
(symbol('IGSB'), symbol('LABU')),
(symbol('IGSB'), symbol('DRIP')),
(symbol('IGSB'), symbol('GUSH')),
(symbol('IGSB'), symbol('XLRE')),
(symbol('IGSB'), symbol('GBIL')),
(symbol('IGSB'), symbol('HYLB')),
(symbol('IGSB'), symbol('DWT')),
(symbol('IGSB'), symbol('UWT')),
(symbol('IGSB'), symbol('JPST')),
(symbol('IGSB'), symbol('XLC')),
(symbol('IEI'), symbol('SHV')),
(symbol('IEI'), symbol('VGSH')),
(symbol('IEI'), symbol('SCHO')),
(symbol('IEI'), symbol('GBIL')),
(symbol('IEI'), symbol('JPST')),
(symbol('SHV'), symbol('VEU')),
(symbol('SHV'), symbol('MBB')),
(symbol('SHV'), symbol('BLV')),
(symbol('SHV'), symbol('BIV')),
(symbol('SHV'), symbol('BSV')),
(symbol('SHV'), symbol('BND')),
(symbol('SHV'), symbol('HYG')),
(symbol('SHV'), symbol('UNG')),
(symbol('SHV'), symbol('SPDW')),
(symbol('SHV'), symbol('RSX')),
(symbol('SHV'), symbol('DXJ')),
(symbol('SHV'), symbol('VEA')),
(symbol('SHV'), symbol('MUB')),
(symbol('SHV'), symbol('PCY')),
(symbol('SHV'), symbol('JNK')),
(symbol('SHV'), symbol('SCZ')),
(symbol('SHV'), symbol('EMB')),
(symbol('SHV'), symbol('EPI')),
(symbol('SHV'), symbol('ACWI')),
(symbol('SHV'), symbol('ACWX')),
(symbol('SHV'), symbol('TBT')),
(symbol('SHV'), symbol('VT')),
(symbol('SHV'), symbol('AAXJ')),
(symbol('SHV'), symbol('FAS')),
(symbol('SHV'), symbol('SPXS')),
(symbol('SHV'), symbol('TZA')),
(symbol('SHV'), symbol('ERX')),
(symbol('SHV'), symbol('SPXL')),
(symbol('SHV'), symbol('TNA')),
(symbol('SHV'), symbol('UCO')),
(symbol('SHV'), symbol('SCO')),
(symbol('SHV'), symbol('SPIB')),
(symbol('SHV'), symbol('AMJ')),
(symbol('SHV'), symbol('VSS')),
(symbol('SHV'), symbol('CWB')),
(symbol('SHV'), symbol('SPXU')),
(symbol('SHV'), symbol('UPRO')),
(symbol('SHV'), symbol('SCHB')),
(symbol('SHV'), symbol('SCHX')),
(symbol('SHV'), symbol('SCHF')),
(symbol('SHV'), symbol('GDXJ')),
(symbol('SHV'), symbol('VMBS')),
(symbol('SHV'), symbol('VCSH')),
(symbol('SHV'), symbol('VGSH')),
(symbol('SHV'), symbol('VCIT')),
(symbol('SHV'), symbol('YINN')),
(symbol('SHV'), symbol('SCHG')),
(symbol('SHV'), symbol('SPSB')),
(symbol('SHV'), symbol('SCHE')),
(symbol('SHV'), symbol('SQQQ')),
(symbol('SHV'), symbol('SDOW')),
(symbol('SHV'), symbol('TQQQ')),
(symbol('SHV'), symbol('UDOW')),
(symbol('SHV'), symbol('SOXL')),
(symbol('SHV'), symbol('SOXS')),
(symbol('SHV'), symbol('EMLC')),
(symbol('SHV'), symbol('SCHO')),
(symbol('SHV'), symbol('AMLP')),
(symbol('SHV'), symbol('VOO')),
(symbol('SHV'), symbol('TVIX')),
(symbol('SHV'), symbol('NUGT')),
(symbol('SHV'), symbol('DUST')),
(symbol('SHV'), symbol('VIXY')),
(symbol('SHV'), symbol('VXUS')),
(symbol('SHV'), symbol('BKLN')),
(symbol('SHV'), symbol('HDV')),
(symbol('SHV'), symbol('MCHI')),
(symbol('SHV'), symbol('SPLV')),
(symbol('SHV'), symbol('DBEF')),
(symbol('SHV'), symbol('FLOT')),
(symbol('SHV'), symbol('SCHZ')),
(symbol('SHV'), symbol('SVXY')),
(symbol('SHV'), symbol('UVXY')),
(symbol('SHV'), symbol('EEMV')),
(symbol('SHV'), symbol('USMV')),
(symbol('SHV'), symbol('EFAV')),
(symbol('SHV'), symbol('SCHD')),
(symbol('SHV'), symbol('FLRN')),
(symbol('SHV'), symbol('OIH')),
(symbol('SHV'), symbol('SMH')),
(symbol('SHV'), symbol('INDA')),
(symbol('SHV'), symbol('DGAZ')),
(symbol('SHV'), symbol('GOVT')),
(symbol('SHV'), symbol('SJNK')),
(symbol('SHV'), symbol('IXUS')),
(symbol('SHV'), symbol('IEFA')),
(symbol('SHV'), symbol('IEMG')),
(symbol('SHV'), symbol('BRZU')),
(symbol('SHV'), symbol('MTUM')),
(symbol('SHV'), symbol('VLUE')),
(symbol('SHV'), symbol('BNDX')),
(symbol('SHV'), symbol('QUAL')),
(symbol('SHV'), symbol('KWEB')),
(symbol('SHV'), symbol('NEAR')),
(symbol('SHV'), symbol('JNUG')),
(symbol('SHV'), symbol('JDST')),
(symbol('SHV'), symbol('NOBL')),
(symbol('SHV'), symbol('ASHR')),
(symbol('SHV'), symbol('DGRO')),
(symbol('SHV'), symbol('FTSM')),
(symbol('SHV'), symbol('LABD')),
(symbol('SHV'), symbol('LABU')),
(symbol('SHV'), symbol('DRIP')),
(symbol('SHV'), symbol('GUSH')),
(symbol('SHV'), symbol('XLRE')),
(symbol('SHV'), symbol('GBIL')),
(symbol('SHV'), symbol('HYLB')),
(symbol('SHV'), symbol('DWT')),
(symbol('SHV'), symbol('UWT')),
(symbol('SHV'), symbol('JPST')),
(symbol('SHV'), symbol('XLC')),
(symbol('VEU'), symbol('CWB')),
(symbol('VEU'), symbol('VXUS')),
(symbol('VEU'), symbol('SCHD')),
(symbol('VEU'), symbol('HYLB')),
(symbol('MBB'), symbol('VMBS')),
(symbol('BLV'), symbol('JPST')),
(symbol('BIV'), symbol('GBIL')),
(symbol('BIV'), symbol('JPST')),
(symbol('BSV'), symbol('SCHO')),
(symbol('BSV'), symbol('GBIL')),
(symbol('BSV'), symbol('JPST')),
(symbol('BND'), symbol('SCHZ')),
(symbol('BND'), symbol('GBIL')),
(symbol('BND'), symbol('JPST')),
(symbol('HYG'), symbol('VIXY')),
(symbol('HYG'), symbol('NEAR')),
(symbol('HYG'), symbol('FTSM')),
(symbol('HYG'), symbol('HYLB')),
(symbol('SPDW'), symbol('VEA')),
(symbol('SPDW'), symbol('FLRN')),
(symbol('SPDW'), symbol('SJNK')),
(symbol('SPDW'), symbol('IEFA')),
(symbol('RSX'), symbol('JPST')),
(symbol('BIL'), symbol('DXJ')),
(symbol('BIL'), symbol('VEA')),
(symbol('BIL'), symbol('MUB')),
(symbol('BIL'), symbol('PCY')),
(symbol('BIL'), symbol('JNK')),
(symbol('BIL'), symbol('SCZ')),
(symbol('BIL'), symbol('EMB')),
(symbol('BIL'), symbol('EPI')),
(symbol('BIL'), symbol('ACWI')),
(symbol('BIL'), symbol('ACWX')),
(symbol('BIL'), symbol('TBT')),
(symbol('BIL'), symbol('VT')),
(symbol('BIL'), symbol('AAXJ')),
(symbol('BIL'), symbol('FAS')),
(symbol('BIL'), symbol('SPXS')),
(symbol('BIL'), symbol('TZA')),
(symbol('BIL'), symbol('ERX')),
(symbol('BIL'), symbol('SPXL')),
(symbol('BIL'), symbol('TNA')),
(symbol('BIL'), symbol('UCO')),
(symbol('BIL'), symbol('SCO')),
(symbol('BIL'), symbol('SPIB')),
(symbol('BIL'), symbol('AMJ')),
(symbol('BIL'), symbol('VSS')),
(symbol('BIL'), symbol('CWB')),
(symbol('BIL'), symbol('SPXU')),
(symbol('BIL'), symbol('UPRO')),
(symbol('BIL'), symbol('SCHB')),
(symbol('BIL'), symbol('SCHX')),
(symbol('BIL'), symbol('SCHF')),
(symbol('BIL'), symbol('GDXJ')),
(symbol('BIL'), symbol('MINT')),
(symbol('BIL'), symbol('VMBS')),
(symbol('BIL'), symbol('VCSH')),
(symbol('BIL'), symbol('VGSH')),
(symbol('BIL'), symbol('VCIT')),
(symbol('BIL'), symbol('YINN')),
(symbol('BIL'), symbol('SCHG')),
(symbol('BIL'), symbol('SPSB')),
(symbol('BIL'), symbol('SCHE')),
(symbol('BIL'), symbol('SQQQ')),
(symbol('BIL'), symbol('SDOW')),
(symbol('BIL'), symbol('TQQQ')),
(symbol('BIL'), symbol('UDOW')),
(symbol('BIL'), symbol('SOXL')),
(symbol('BIL'), symbol('SOXS')),
(symbol('BIL'), symbol('EMLC')),
(symbol('BIL'), symbol('SCHO')),
(symbol('BIL'), symbol('AMLP')),
(symbol('BIL'), symbol('VOO')),
(symbol('BIL'), symbol('TVIX')),
(symbol('BIL'), symbol('NUGT')),
(symbol('BIL'), symbol('DUST')),
(symbol('BIL'), symbol('VIXY')),
(symbol('BIL'), symbol('VXUS')),
(symbol('BIL'), symbol('BKLN')),
(symbol('BIL'), symbol('HDV')),
(symbol('BIL'), symbol('MCHI')),
(symbol('BIL'), symbol('SPLV')),
(symbol('BIL'), symbol('DBEF')),
(symbol('BIL'), symbol('FLOT')),
(symbol('BIL'), symbol('SCHZ')),
(symbol('BIL'), symbol('SVXY')),
(symbol('BIL'), symbol('UVXY')),
(symbol('BIL'), symbol('EEMV')),
(symbol('BIL'), symbol('USMV')),
(symbol('BIL'), symbol('EFAV')),
(symbol('BIL'), symbol('SCHD')),
(symbol('BIL'), symbol('FLRN')),
(symbol('BIL'), symbol('OIH')),
(symbol('BIL'), symbol('SMH')),
(symbol('BIL'), symbol('INDA')),
(symbol('BIL'), symbol('DGAZ')),
(symbol('BIL'), symbol('GOVT')),
(symbol('BIL'), symbol('SJNK')),
(symbol('BIL'), symbol('IXUS')),
(symbol('BIL'), symbol('IEFA')),
(symbol('BIL'), symbol('IEMG')),
(symbol('BIL'), symbol('BRZU')),
(symbol('BIL'), symbol('MTUM')),
(symbol('BIL'), symbol('VLUE')),
(symbol('BIL'), symbol('BNDX')),
(symbol('BIL'), symbol('QUAL')),
(symbol('BIL'), symbol('KWEB')),
(symbol('BIL'), symbol('NEAR')),
(symbol('BIL'), symbol('JNUG')),
(symbol('BIL'), symbol('JDST')),
(symbol('BIL'), symbol('NOBL')),
(symbol('BIL'), symbol('ASHR')),
(symbol('BIL'), symbol('DGRO')),
(symbol('BIL'), symbol('FTSM')),
(symbol('BIL'), symbol('LABD')),
(symbol('BIL'), symbol('LABU')),
(symbol('BIL'), symbol('DRIP')),
(symbol('BIL'), symbol('GUSH')),
(symbol('BIL'), symbol('XLRE')),
(symbol('BIL'), symbol('GBIL')),
(symbol('BIL'), symbol('HYLB')),
(symbol('BIL'), symbol('DWT')),
(symbol('BIL'), symbol('UWT')),
(symbol('BIL'), symbol('JPST')),
(symbol('BIL'), symbol('XLC')),
(symbol('DXJ'), symbol('ERX')),
(symbol('VEA'), symbol('FLRN')),
(symbol('VEA'), symbol('SJNK')),
(symbol('MUB'), symbol('JPST')),
(symbol('PCY'), symbol('VCSH')),
(symbol('PCY'), symbol('SPSB')),
(symbol('PCY'), symbol('JPST')),
(symbol('EMB'), symbol('SPIB')),
(symbol('EMB'), symbol('VCSH')),
(symbol('EMB'), symbol('VCIT')),
(symbol('EMB'), symbol('SPSB')),
(symbol('EMB'), symbol('JPST')),
(symbol('ACWI'), symbol('MINT')),
(symbol('ACWI'), symbol('VIXY')),
(symbol('ACWI'), symbol('DBEF')),
(symbol('ACWI'), symbol('SCHD')),
(symbol('ACWI'), symbol('NEAR')),
(symbol('ACWI'), symbol('FTSM')),
(symbol('ACWI'), symbol('HYLB')),
(symbol('ACWX'), symbol('CWB')),
(symbol('ACWX'), symbol('SCHD')),
(symbol('ACWX'), symbol('NEAR')),
(symbol('ACWX'), symbol('FTSM')),
(symbol('ACWX'), symbol('HYLB')),
(symbol('VT'), symbol('CWB')),
(symbol('VT'), symbol('MINT')),
(symbol('VT'), symbol('NEAR')),
(symbol('VT'), symbol('FTSM')),
(symbol('FAS'), symbol('MINT')),
(symbol('FAS'), symbol('FTSM')),
(symbol('SPXS'), symbol('SPXU')),
(symbol('SPXS'), symbol('TVIX')),
(symbol('SPXS'), symbol('VIXY')),
(symbol('SPXS'), symbol('NEAR')),
(symbol('SPXS'), symbol('FTSM')),
(symbol('TZA'), symbol('JNUG')),
(symbol('SPXL'), symbol('MINT')),
(symbol('SPXL'), symbol('FTSM')),
(symbol('SPIB'), symbol('VCIT')),
(symbol('SPIB'), symbol('SPSB')),
(symbol('SPIB'), symbol('GBIL')),
(symbol('SPIB'), symbol('JPST')),
(symbol('VSS'), symbol('AMLP')),
(symbol('CWB'), symbol('SCHD')),
(symbol('SPXU'), symbol('TVIX')),
(symbol('SPXU'), symbol('VIXY')),
(symbol('SPXU'), symbol('NEAR')),
(symbol('SPXU'), symbol('FTSM')),
(symbol('UPRO'), symbol('MINT')),
(symbol('UPRO'), symbol('FTSM')),
(symbol('SCHB'), symbol('MINT')),
(symbol('SCHB'), symbol('DBEF')),
(symbol('SCHB'), symbol('NEAR')),
(symbol('SCHB'), symbol('FTSM')),
(symbol('SCHX'), symbol('MINT')),
(symbol('SCHX'), symbol('VOO')),
(symbol('SCHX'), symbol('VIXY')),
(symbol('SCHX'), symbol('NEAR')),
(symbol('SCHX'), symbol('FTSM')),
(symbol('SCHF'), symbol('TQQQ')),
(symbol('SCHF'), symbol('FLOT')),
(symbol('SCHF'), symbol('FLRN')),
(symbol('SCHF'), symbol('SJNK')),
(symbol('MINT'), symbol('SCHG')),
(symbol('MINT'), symbol('TQQQ')),
(symbol('MINT'), symbol('UDOW')),
(symbol('MINT'), symbol('VOO')),
(symbol('MINT'), symbol('TVIX')),
(symbol('MINT'), symbol('VIXY')),
(symbol('MINT'), symbol('DBEF')),
(symbol('MINT'), symbol('EFAV')),
(symbol('MINT'), symbol('SCHD')),
(symbol('MINT'), symbol('MTUM')),
(symbol('MINT'), symbol('QUAL')),
(symbol('MINT'), symbol('NOBL')),
(symbol('MINT'), symbol('DGRO')),
(symbol('MINT'), symbol('FTSM')),
(symbol('MINT'), symbol('JPST')),
(symbol('MINT'), symbol('XLC')),
(symbol('VCSH'), symbol('SPSB')),
(symbol('VCSH'), symbol('GBIL')),
(symbol('VCSH'), symbol('JPST')),
(symbol('VGSH'), symbol('SCHO')),
(symbol('VGSH'), symbol('GOVT')),
(symbol('VGSH'), symbol('GBIL')),
(symbol('VGSH'), symbol('JPST')),
(symbol('VCIT'), symbol('SPSB')),
(symbol('VCIT'), symbol('GBIL')),
(symbol('VCIT'), symbol('JPST')),
(symbol('SCHG'), symbol('VIXY')),
(symbol('SCHG'), symbol('NEAR')),
(symbol('SCHG'), symbol('FTSM')),
(symbol('SPSB'), symbol('GBIL')),
(symbol('SPSB'), symbol('JPST')),
(symbol('SCHE'), symbol('SMH')),
(symbol('SCHE'), symbol('NEAR')),
(symbol('SCHE'), symbol('LABD')),
(symbol('SQQQ'), symbol('SDOW')),
(symbol('UDOW'), symbol('FTSM')),
(symbol('EMLC'), symbol('GUSH')),
(symbol('SCHO'), symbol('GOVT')),
(symbol('SCHO'), symbol('GBIL')),
(symbol('SCHO'), symbol('JPST')),
(symbol('VOO'), symbol('VIXY')),
(symbol('VOO'), symbol('NEAR')),
(symbol('VOO'), symbol('FTSM')),
(symbol('TVIX'), symbol('EFAV')),
(symbol('TVIX'), symbol('NEAR')),
(symbol('TVIX'), symbol('FTSM')),
(symbol('VIXY'), symbol('EFAV')),
(symbol('VIXY'), symbol('QUAL')),
(symbol('VIXY'), symbol('NEAR')),
(symbol('VIXY'), symbol('DGRO')),
(symbol('VIXY'), symbol('FTSM')),
(symbol('VIXY'), symbol('HYLB')),
(symbol('VIXY'), symbol('XLC')),
(symbol('VXUS'), symbol('IXUS')),
(symbol('VXUS'), symbol('HYLB')),
(symbol('BKLN'), symbol('FLOT')),
(symbol('BKLN'), symbol('FLRN')),
(symbol('SPLV'), symbol('JPST')),
(symbol('DBEF'), symbol('SCHD')),
(symbol('DBEF'), symbol('QUAL')),
(symbol('DBEF'), symbol('NEAR')),
(symbol('DBEF'), symbol('FTSM')),
(symbol('FLOT'), symbol('FLRN')),
(symbol('FLOT'), symbol('FTSM')),
(symbol('SCHZ'), symbol('GBIL')),
(symbol('SCHZ'), symbol('JPST')),
(symbol('USMV'), symbol('JPST')),
(symbol('EFAV'), symbol('NEAR')),
(symbol('EFAV'), symbol('FTSM')),
(symbol('EFAV'), symbol('HYLB')),
(symbol('SCHD'), symbol('FTSM')),
(symbol('FLRN'), symbol('FTSM')),
(symbol('DGAZ'), symbol('GBIL')),
(symbol('GOVT'), symbol('GBIL')),
(symbol('IXUS'), symbol('HYLB')),
(symbol('IEMG'), symbol('LABD')),
(symbol('MTUM'), symbol('NEAR')),
(symbol('MTUM'), symbol('FTSM')),
(symbol('BNDX'), symbol('JPST')),
(symbol('QUAL'), symbol('NEAR')),
(symbol('QUAL'), symbol('FTSM')),
(symbol('NEAR'), symbol('NOBL')),
(symbol('NEAR'), symbol('DGRO')),
(symbol('NEAR'), symbol('FTSM')),
(symbol('NEAR'), symbol('HYLB')),
(symbol('NEAR'), symbol('JPST')),
(symbol('NEAR'), symbol('XLC')),
(symbol('JNUG'), symbol('DRIP')),
(symbol('NOBL'), symbol('FTSM')),
(symbol('DGRO'), symbol('FTSM')),
(symbol('FTSM'), symbol('LABD')),
(symbol('FTSM'), symbol('XLRE')),
(symbol('FTSM'), symbol('GBIL')),
(symbol('FTSM'), symbol('HYLB')),
(symbol('FTSM'), symbol('DWT')),
(symbol('FTSM'), symbol('JPST')),
(symbol('FTSM'), symbol('XLC')),
(symbol('XLRE'), symbol('JPST')),
(symbol('GBIL'), symbol('HYLB')),
(symbol('GBIL'), symbol('DWT')),
(symbol('GBIL'), symbol('UWT')),
(symbol('GBIL'), symbol('JPST')),
(symbol('GBIL'), symbol('XLC')),
(symbol('HYLB'), symbol('XLC'))]
    
    context.stocks = symbols('DIA',
'SPY',
'MDY',
'EWA',
'EWC',
'EWG',
'EWJ',
'EWU',
'EWW',
'XLE',
'XLF',
'XLI',
'XLK',
'XLU',
'XLY',
'QQQ',
'IJH',
'IJR',
'IVE',
'IVV',
'IVW',
'IWB',
'IWD',
'IWF',
'IWM',
'IWV',
'IYF',
'EWT',
'IYR',
'EZU',
'IWN',
'IWO',
'IUSV',
'IUSG',
'SPYG',
'SPYV',
'OEF',
'VTI',
'IGV',
'IWP',
'IWR',
'IWS',
'EFA',
'VXF',
'IEF',
'LQD',
'SHY',
'EZA',
'EEM',
'RSP',
'AGG',
'DVY',
'TIP',
'ITOT',
'VB',
'VBR',
'VFH',
'VGT',
'VHT',
'VO',
'VTV',
'VUG',
'VV',
'FEZ',
'VNQ',
'FXI',
'GLD',
'IAU',
'VGK',
'VWO',
'KBE',
'SDY',
'XBI',
'XHB',
'USO',
'VIG',
'ITB',
'ITA',
'GDX',
'PSQ',
'DOG',
'SH',
'DDM',
'SSO',
'QLD',
'XME',
'XRT',
'KRE',
'XOP',
'FDN',
'QID',
'SDS',
'VOE',
'PFF',
'VYM',
'IGSB',
'IEI',
'SHV',
'VEU',
'MBB',
'BLV',
'BIV',
'BSV',
'BND',
'HYG',
'UNG',
'SPDW',
'RSX',
'BIL',
'DXJ',
'VEA',
'MUB',
'PCY',
'JNK',
'SCZ',
'EMB',
'EPI',
'ACWI',
'ACWX',
'TBT',
'VT',
'AAXJ',
'FAS',
'SPXS',
'TZA',
'ERX',
'SPXL',
'TNA',
'UCO',
'SCO',
'SPIB',
'AMJ',
'VSS',
'CWB',
'SPXU',
'UPRO',
'SCHB',
'SCHX',
'SCHF',
'GDXJ',
'MINT',
'VMBS',
'VCSH',
'VGSH',
'VCIT',
'YINN',
'SCHG',
'SPSB',
'SCHE',
'SQQQ',
'SDOW',
'TQQQ',
'UDOW',
'SOXL',
'SOXS',
'EMLC',
'SCHO',
'AMLP',
'VOO',
'TVIX',
'NUGT',
'DUST',
'VIXY',
'VXUS',
'BKLN',
'HDV',
'MCHI',
'SPLV',
'DBEF',
'FLOT',
'SCHZ',
'SVXY',
'UVXY',
'EEMV',
'USMV',
'EFAV',
'SCHD',
'FLRN',
'OIH',
'SMH',
'INDA',
'DGAZ',
'GOVT',
'SJNK',
'IXUS',
'IEFA',
'IEMG',
'BRZU',
'MTUM',
'VLUE',
'BNDX',
'QUAL',
'KWEB',
'NEAR',
'JNUG',
'JDST',
'NOBL',
'ASHR',
'DGRO',
'FTSM',
'LABD',
'LABU',
'DRIP',
'GUSH',
'XLRE',
'GBIL',
'HYLB',
'DWT',
'UWT',
'JPST',
'XLC')
    
    context.num_pairs = len(context.stock_pairs)
    # strategy specific variables
    context.lookback = 5 # used for regression
    context.z_window = 5 # used for zscore calculation, must be <= lookback
    
    context.target_weights = pd.Series(index=context.stocks, data=0.25)
    
    context.spread = np.ndarray((context.num_pairs, 0))
    context.inLong = [False] * context.num_pairs
    context.inShort = [False] * context.num_pairs
    
    # Only do work 30 minutes before close
    schedule_function(func=check_pair_status, date_rule=date_rules.every_day(), time_rule=time_rules.market_open(minutes=90))
    
# Will be called on every trade event for the securities you specify. 
def handle_data(context, data):
    # Our work is now scheduled in check_pair_status
    pass

def check_pair_status(context, data):
    
    prices = data.history(context.stocks, 'price', 35, '1d').iloc[-context.lookback::]
    
    new_spreads = np.ndarray((context.num_pairs, 1))
    
    for i in range(context.num_pairs):

        (stock_y, stock_x) = context.stock_pairs[i]

        Y = prices[stock_y]
        X = prices[stock_x]
        
        # Comment explaining try block
        try:
            hedge = hedge_ratio(Y, X, add_const=True)      
        except ValueError as e:
            log.debug(e)
            return

        context.target_weights = get_current_portfolio_weights(context, data)
        
        new_spreads[i, :] = Y[-1] - hedge * X[-1]

        if context.spread.shape[1] > context.z_window:
            # Keep only the z-score lookback period
            spreads = context.spread[i, -context.z_window:]

            zscore = (spreads[-1] - spreads.mean()) / spreads.std()

            if context.inShort[i] and zscore < 0.0:
                context.target_weights[stock_y] = 0
                context.target_weights[stock_x] = 0
                
                context.inShort[i] = False
                context.inLong[i] = False
                
                record(X_pct=0, Y_pct=0)
                allocate(context, data)
                return

            if context.inLong[i] and zscore > 0.0:
                context.target_weights[stock_y] = 0
                context.target_weights[stock_x] = 0
                
                
                context.inShort[i] = False
                context.inLong[i] = False
                
                record(X_pct=0, Y_pct=0)
                allocate(context, data)
                return

            if zscore < -1.0 and (not context.inLong[i]):
                # Only trade if NOT already in a trade 
                y_target_shares = 1
                X_target_shares = -hedge
                context.inLong[i] = True
                context.inShort[i] = False

                (y_target_pct, x_target_pct) = computeHoldingsPct(y_target_shares,X_target_shares, Y[-1], X[-1])
                
                context.target_weights[stock_y] = y_target_pct * (1.0/context.num_pairs)
                context.target_weights[stock_x] = x_target_pct * (1.0/context.num_pairs)
                
                record(Y_pct=y_target_pct, X_pct=x_target_pct)
                allocate(context, data)
                return
                

            if zscore > 1.0 and (not context.inShort[i]):
                # Only trade if NOT already in a trade
                y_target_shares = -1
                X_target_shares = hedge
                context.inShort[i] = True
                context.inLong[i] = False

                (y_target_pct, x_target_pct) = computeHoldingsPct( y_target_shares, X_target_shares, Y[-1], X[-1] )
                
                context.target_weights[stock_y] = y_target_pct * (1.0/context.num_pairs)
                context.target_weights[stock_x] = x_target_pct * (1.0/context.num_pairs)
                
                record(Y_pct=y_target_pct, X_pct=x_target_pct)
                allocate(context, data)
                return
        
    context.spread = np.hstack([context.spread, new_spreads])

def hedge_ratio(Y, X, add_const=True):
    if add_const:
        X = sm.add_constant(X)
        model = sm.OLS(Y, X).fit()
        return model.params[1]
    model = sm.OLS(Y, X).fit()
    return model.params.values
   
def computeHoldingsPct(yShares, xShares, yPrice, xPrice):
    yDol = yShares * yPrice
    xDol = xShares * xPrice
    notionalDol =  abs(yDol) + abs(xDol)
    y_target_pct = yDol / notionalDol
    x_target_pct = xDol / notionalDol
    return (y_target_pct, x_target_pct)

def get_current_portfolio_weights(context, data):  
    positions = context.portfolio.positions  
    positions_index = pd.Index(positions)  
    share_counts = pd.Series(  
        index=positions_index,  
        data=[positions[asset].amount for asset in positions]  
    )

    current_prices = data.current(positions_index, 'price')  
    current_weights = share_counts * current_prices / context.portfolio.portfolio_value  
    return current_weights.reindex(positions_index.union(context.stocks), fill_value=0.0)  

def allocate(context, data):    
    # Set objective to match target weights as closely as possible, given constraints
    objective = opt.TargetWeights(context.target_weights)
    
    # Define constraints
    constraints = []
    constraints.append(opt.MaxGrossExposure(1.0))
    
    
    algo.order_optimal_portfolio(
        objective=objective,
        constraints=constraints,
    )